#!/bin/bash

##############################################################################
# create-project.sh — T048 GitHub Project Creation Orchestrator
#
# Purpose: Create GitHub repository with spec-kit scaffolding
#
# Usage: ./scripts/create-project.sh "Project Name" "Brief description"
#   Example: ./scripts/create-project.sh "awesome-cli" "CLI tool for X"
#
# Output:
#   - GitHub repo created: victortamotsu/awesome-cli
#   - Local clone: /mnt/external/projects/awesome-cli/
#   - spec-kit initialized with copilot AI
#   - Initial commit with spec.md scaffolding
#
# Dependencies:
#   - gh CLI installed + authenticated
#   - git configured
#   - specify CLI available
#
##############################################################################

set -e

# ─────────────────────────────────────────────────────────────────────
# Configuration
# ─────────────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
PROJECTS_DIR="/mnt/external/projects"
LOG_DIR="/mnt/external/logs/projects"
TIMESTAMP=$(date +%Y-%m-%d_%H%M%S)

# Ensure directories exist
mkdir -p "$PROJECTS_DIR" "$LOG_DIR"

# Input validation
PROJECT_NAME="${1:-}"
DESCRIPTION="${2:-Personal project}"

if [[ -z "$PROJECT_NAME" ]]; then
    echo "Usage: $0 <project-name> [description]"
    echo "Example: $0 awesome-cli 'CLI tool for development'"
    exit 1
fi

# Convert to kebab-case
PROJECT_NAME_KEBAB=$(echo "$PROJECT_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g' | sed 's/-+/-/g' | sed 's/^-\|-$//')

if [[ -z "$PROJECT_NAME_KEBAB" ]]; then
    echo "Error: Invalid project name"
    exit 1
fi

LOG_FILE="$LOG_DIR/$TIMESTAMP-$PROJECT_NAME_KEBAB.log"

{
    echo "=========================================="
    echo "GitHub Project Creation — $PROJECT_NAME_KEBAB"
    echo "=========================================="
    echo "Timestamp: $(date -Iseconds)"
    echo "Name: $PROJECT_NAME_KEBAB"
    echo "Description: $DESCRIPTION"
    echo

    # Step 1: Create GitHub repo
    echo "[1/5] Creating GitHub repository..."
    if gh repo create "victortamotsu/$PROJECT_NAME_KEBAB" \
        --public \
        --description "$DESCRIPTION" \
        --disable-wiki \
        --disable-projects \
        2>&1; then
        echo "✅ GitHub repo created: https://github.com/victortamotsu/$PROJECT_NAME_KEBAB"
    else
        echo "❌ Failed to create GitHub repo"
        exit 1
    fi

    # Step 2: Clone repository
    echo "[2/5] Cloning repository..."
    cd "$PROJECTS_DIR"
    if git clone "https://github.com/victortamotsu/$PROJECT_NAME_KEBAB.git" 2>&1; then
        echo "✅ Repository cloned to: $PROJECTS_DIR/$PROJECT_NAME_KEBAB"
    else
        echo "❌ Failed to clone repository"
        exit 1
    fi

    cd "$PROJECT_NAME_KEBAB"

    # Step 3: Initialize spec-kit
    echo "[3/5] Initializing spec-kit..."
    if specify init . --ai copilot --force 2>&1; then
        echo "✅ spec-kit initialized"
    else
        echo "⚠️ spec-kit initialization had issues (continuing)"
    fi

    # Step 4: Create initial spec.md
    echo "[4/5] Creating initial spec.md..."
    cat > spec.md << 'EOF'
# Project Specification

**Status**: Ideation  
**Created**: $(date +%Y-%m-%d)  
**Owner**: Victor

## Overview

[Project description goes here]

## Scope

- Core features
- MVP requirements
- Success criteria

## Architecture

```
TODO: Add architecture diagram or description
```

## Implementation Plan

- [ ] Phase 1: Setup
- [ ] Phase 2: Core features
- [ ] Phase 3: Testing
- [ ] Phase 4: Deployment

## Notes

Generated automatically by Jarvis OpenClaw Assistant.
Edit this file to add details about the project.

---
EOF
    echo "✅ spec.md created"

    # Step 5: Initial commit
    echo "[5/5] Creating initial commit..."
    git add -A
    git commit -m "init: spec-kit scaffolding and initial spec.md

Generated by Jarvis Project Creator" 2>&1 || echo "ℹ️ Initial commit (may have no changes)"
    git push -u origin main 2>&1 || git push -u origin master 2>&1 || true
    echo "✅ Initial commit pushed"

    echo
    echo "=========================================="
    echo "✅ Project Created Successfully!"
    echo "=========================================="
    echo "Repo:  https://github.com/victortamotsu/$PROJECT_NAME_KEBAB"
    echo "Local: $PROJECTS_DIR/$PROJECT_NAME_KEBAB"
    echo "Spec:  $PROJECTS_DIR/$PROJECT_NAME_KEBAB/spec.md"
    echo

} | tee "$LOG_FILE"

exit 0
